#ifndef ALSDL2CFG_H
#define ALSDL2CFG_H

#include <fcntl.h>
#include <unistd.h>

/* Describe this platform */
#define ALLEGRO_PLATFORM_STR  "SDL2"
#define ALLEGRO_CONSOLE_OK
#define ALLEGRO_USE_CONSTRUCTOR

#define ALLEGRO_EXTRA_HEADER    "allegro/platform/alsdl2.h"

/* Include configuration generated by configure script.  */
#include "allegro/platform/alunixac.h"

/* Enable multithreaded library */
#define ALLEGRO_MULTITHREADED

/* Provide implementations of missing functions.  */
#ifndef ALLEGRO_HAVE_STRICMP
#define ALLEGRO_NO_STRICMP
#endif

#ifndef ALLEGRO_HAVE_STRLWR
#define ALLEGRO_NO_STRLWR
#endif

#ifndef ALLEGRO_HAVE_STRUPR
#define ALLEGRO_NO_STRUPR
#endif

#ifndef ALLEGRO_HAVE_MEMCMP
#define ALLEGRO_NO_MEMCMP
#endif

/* Override default definitions for this platform */
#define AL_RAND()    ((rand() >> 16) & 0x7fff)

#endif
